version: '3.9'

services:
    mongodb:
        image: mongo:latest
        container_name: mongo
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: todo1234
        volumes:
            - mongo-data:/data/db

volumes:
    mongo-data: